version: "3.7"

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  service:
    container_name: errata-service
    build: .
    command: ./service -c config.yml
    ports:
      - "9111:9111"
    depends_on:
      - clickhouse