port: ":9111"
database: "default"
login: "default"
password: ""
#clickhouse_address: "127.0.0.1:18123" //localhost
clickhouse_address: "clickhouse:9000"
dialTimeout: 5
HTTP: false
#Enter gateway compose
#allowed: ["172.20.0.1"]